# Generated by Django 3.0.6 on 2020-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0002_auto_20200518_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='heading',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
